### ISSUE TITLE
Any PYPI updates?

### ISSUE THREAD

**Issue by syabro** [adamalton/django-csp-reports#12]
Current pypi version was released 18 months ago and doesn't work with django>=1.9

**Comment by adamalton** [comment]
Ah, so @knaperek released the 1.0 version to PyPI, which means that I can't make further releases as he's currently got control of the 'django-csp-reports' package name!

@knaperek could you add me as a manager of the package on PyPI please?  My PyPI username is 'adamalton'.

Thanks!

**Comment by knaperek** [comment]
sure @adamalton, you got it.

**Comment by adamalton** [comment]
Thanks!

Version 1.1 has now been released!
