### ISSUE TITLE
Replace utils.Config with third party library

### ISSUE THREAD

**Issue by ziima** [adamalton/django-csp-reports#29]
Application settings are not handled by Django, but there are several apps which tries to solve that. I suggest to use https://github.com/Genida/django-appsettings to handle CSP settings.

**Comment by adamalton** [comment]
I must admit, I see very little value in switching to this. I'm very reluctant to add an additional dependency on a third party library for something which is currently just 13 lines of code and (as far as I'm aware) isn't causing any issues.

I'm open to persuasion, but it would have to be pretty strong 🙂 , so I'm going to close this for now.
