### ISSUE TITLE
With Python 3 Django generates a new migration for ordering

### ISSUE THREAD

**Issue by aaronelliotross** [adamalton/django-csp-reports#36]
Under Python3, Django wants to generate a new version of this migration:

https://github.com/adamalton/django-csp-reports/blob/master/cspreports/migrations/0002_auto_20141011_1800.py#L16

However, the only difference is that 

            options={'ordering': (b'-created',)},

becomes:

             options={'ordering': ('-created',)},

The issue is discussed here:

https://code.djangoproject.com/ticket/23226#comment:18

The solution is to edit the migration to use '-created' and not b'-created', which works for both versions.

Thanks!

**Comment by ziima** [comment]
Thanks.
