### ISSUE TITLE
Provide support for django 2.1

### ISSUE THREAD

**Issue by reginaochotzki** [adamalton/django-csp-reports#39]
Support for django 2.1 would be very helpful since we want to migrate our projekt to django 2.1

**Comment by adamalton** [comment]
It will work with Django 2.1 already.  I'm just updating the Travis config to make it run the tests for 2.1 and 2.2, and updating the README.  The tests pass, so it should already work for you on Django 2.1.

**Comment by reginaochotzki** [comment]
Hi Adam, the problem is that we can not install it without warnings as long the packages says itself, it is not compatible to 2.1 ;-)
We have been using yarn and yarn denies installing the package. Now we are using poetry, but poetry complains also.
Regards Regina
________________________________
Von: Adam Alton [notifications@github.com]
Gesendet: Sonntag, 28. April 2019 11:52
An: adamalton/django-csp-reports
Cc: Ochotzki, Regina; Author
Betreff: Re: [adamalton/django-csp-reports] Provide support for django 2.1 (#39)


It will work with Django 2.1 already. I'm just updating the Travis config to make it run the tests for 2.1 and 2.2, and updating the README. The tests pass, so it should already work for you on Django 2.1.

**Comment by reginaochotzki** [comment]
sorry I was a litte bit confused. We are using yarn and yarn complains about the missing compatibility to 2.1
________________________________
Von: Ochotzki, Regina
Gesendet: Donnerstag, 2. Mai 2019 09:46
An: adamalton/django-csp-reports
Betreff: AW: [adamalton/django-csp-reports] Provide support for django 2.1 (#39)

Hi Adam, the problem is that we can not install it without warnings as long the packages says itself, it is not compatible to 2.1 ;-)
We have been using yarn and yarn denies installing the package. Now we are using poetry, but poetry complains also.
Regards Regina
________________________________
Von: Adam Alton [notifications@github.com]
Gesendet: Sonntag, 28. April 2019 11:52
An: adamalton/django-csp-reports
Cc: Ochotzki, Regina; Author
Betreff: Re: [adamalton/django-csp-reports] Provide support for django 2.1 (#39)


It will work with Django 2.1 already. I'm just updating the Travis config to make it run the tests for 2.1 and 2.2, and updating the README. The tests pass, so it should already work for you on Django 2.1.

**Comment by adamalton** [comment]
Apologies for taking so long to do this.  I've now done a release of version 1.3, which officially supports Django 2.0, 2.1 and 2.2
