### ISSUE TITLE
Summary template is missing from pypi package

### ISSUE THREAD

**Issue by Bartvaderkin** [adamalton/django-csp-reports#46]
The `cspreports/summary.txt` is missing from the version 1.5 pypi package.

I'd guess because of the manifest in this recent commit: https://github.com/adamalton/django-csp-reports/commit/414d23d82b261038e59589059704d7c134f8f380

**Comment by adamalton** [comment]
Very good point. Let me fix that…

**Comment by adamalton** [comment]
It looks like I forgot to close this issue when I fixed the bug. Closing.
