### ISSUE TITLE
Django 4.0 support?

### ISSUE THREAD

**Issue by rloomans** [adamalton/django-csp-reports#49]
The tests seem to run fine for Django 4.0. 

Is it just a matter of bumping the requirement on Django to allow 4.0?

**Comment by adamalton** [comment]
Yes, probably. From what I remember reading in the Django 4.0 release notes, I don't think there's anything that would prevent this app from working. I'll take a look…

**Comment by adamalton** [comment]
Done. Released as version 1.7.
