### ISSUE TITLE
Extra migration file when changing DEFAULT_AUTO_FIELD in Django 3.2

### ISSUE THREAD

**Issue by niconil** [adamalton/django-csp-reports#52]
when migrating an existing Django project from 
django 2.2 to django 3.2

and specifying in settings :
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

this will generate a migration file inside 'cspreports' module.
IMHO i think this migration should not happen

**Comment by adamalton** [comment]
Yep, makes sense, I agree.
