### ISSUE TITLE
Migrations Outdated

### ISSUE THREAD

**Issue by astronouth7303** [adamalton/django-csp-reports#7]
The migrations have unsynced changes.

**Comment by adamalton** [comment]
I can't see a difference between the model definition and the model that would be created by the migration files (although I'm only reading the code on GitHub, not running it).  What's missing?

This isn't just because you haven't yet run the migrations is it?

**Comment by astronouth7303** [comment]
Ah, that's it.

I think it's generally traditionally to package and version migrations with your app, so that when an a user updates their copy, Django knows what incremental database changes need to be made.

**Comment by adamalton** [comment]
Ah good, I didn't think the migrations were wrong.

I haven't got around to doing a release to PyPi yet.  I'm on holiday at the moment, but will endeavour to do it when I'm back.

**Comment by adamalton** [comment]
I've made a separate issue to do a release to PyPi.
